DA: false
batchsize: 8
color_jitter: false
data_dir: /data/modanqi/projects/University1652-Baseline/data/train
droprate: 0.75
erasing_p: 0
extra_Google: false
fp16: false
gpu_ids: '0'
h: 256
lr: 0.01
moving_avg: 1.0
name: two_view_long_no_street_share_d0.75_256_s1
nclasses: 701
pad: 10
pool: avg
resume: false
share: true
stride: 1
train_all: false
use_NAS: false
use_dense: false
views: 3
w: 256
warm_epoch: 0
