DA: false
arcface: false
batchsize: 16
circle: false
color_jitter: false
contrast: false
cosface: true
data_dir: /data/modanqi/projects/University1652-Baseline/data/train
droprate: 0.75
erasing_p: 0
extra_Google: true
fp16: false
gpu_ids: '0'
h: 256
lifted: false
loss_merge: false
lr: 0.01
moving_avg: 1.0
name: three_view_long_share_d0.75_256_s1_google_bz16_convnextTiny_cosface
nclasses: 701
pad: 10
pool: avg
resume: false
share: true
sphere: false
stride: 1
train_all: false
triplet: false
use_NAS: false
use_dense: false
views: 3
w: 256
warm_epoch: 0
